plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.r36s.usb0manager'
    compileSdk 35

    defaultConfig {
        applicationId 'com.r36s.usb0manager'
        minSdk 30
        targetSdk 30
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
